trigger:
  - master
  
pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

jobs:

- job: backend
  displayName: Backend_Build 
  container: 
  workspace:
    clean: all
  steps:
  - template: backend.yml@EATWELL